version: '3'
services:
  db:
    image: postgres:12
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: farm
    restart: always

  www:
    depends_on:
      - db
    image: farmos/farmos:2.0.0-beta3
    volumes:
      - './sites:/opt/drupal/web/sites'
    expose:
      - 80
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
